version: '2'
services:
  spark-master:
    build:
      context: .
      dockerfile: docker/master/Dockerfile
    container_name: spark-master
    ports:
    - "8080:8080"
    - "7077:7077"
  spark-worker-1:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: spark-worker-1
    depends_on:
    - spark-master
    ports:
    - "8081:8081"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"